In [1]:
import os
import sys
ROOT_DIR = os.path.abspath("../")
sys.path.append(ROOT_DIR)
import h5py
import numpy as np

from sort.sort import Sort

In [2]:
data_import_path = '../../Data/30SLight1.hdf5'

f = h5py.File(data_import_path, "r")


In [3]:
print(len(list(f.keys())))

141


In [4]:
cls_names =f["class_names"]
print(cls_names.value)
print(np.where(cls_names.value == b'car' )[0][0])
print(np.where(cls_names.value == b'traffic light' )[0][0])
print(np.where(cls_names.value == b'bus' )[0][0])
np.where(cls_names.value == b'truck' )[0][0]


[b'BG' b'person' b'bicycle' b'car' b'motorcycle' b'airplane' b'bus'
 b'train' b'truck' b'boat' b'traffic light' b'fire hydrant' b'stop sign'
 b'parking meter' b'bench' b'bird' b'cat' b'dog' b'horse' b'sheep' b'cow'
 b'elephant' b'bear' b'zebra' b'giraffe' b'backpack' b'umbrella' b'handbag'
 b'tie' b'suitcase' b'frisbee' b'skis' b'snowboard' b'sports ball' b'kite'
 b'baseball bat' b'baseball glove' b'skateboard' b'surfboard'
 b'tennis racket' b'bottle' b'wine glass' b'cup' b'fork' b'knife' b'spoon'
 b'bowl' b'banana' b'apple' b'sandwich' b'orange' b'broccoli' b'carrot'
 b'hot dog' b'pizza' b'donut' b'cake' b'chair' b'couch' b'potted plant'
 b'bed' b'dining table' b'toilet' b'tv' b'laptop' b'mouse' b'remote'
 b'keyboard' b'cell phone' b'microwave' b'oven' b'toaster' b'sink'
 b'refrigerator' b'book' b'clock' b'vase' b'scissors' b'teddy bear'
 b'hair drier' b'toothbrush']
3
10
6


8

In [5]:
list(f['frame1'].keys())

['class_ids', 'image', 'masks', 'rois', 'scores']

In [6]:
f['frame1']['class_ids'].value.shape

(10,)

In [7]:
f['frame1']['image'].value.shape

(540, 930, 3)

In [8]:
f['frame1']['masks'].value.shape

(540, 930, 10)

In [9]:
f['frame1']['scores'].value.shape

(10,)

In [10]:
f['frame1']['rois'].value


array([[ 57, 249, 322, 587],
       [157,  84, 220, 174],
       [166, 623, 234, 641],
       [  7,  57, 114,  96],
       [ 31,   1, 161,  55],
       [157, 609, 186, 620],
       [157, 229, 186, 242],
       [158, 598, 186, 608],
       [153,  29, 183,  62],
       [145, 164, 196, 221]], dtype=int32)

In [11]:
print(f['frame1']['class_ids'].value)
print(np.isin(f['frame1']['class_ids'].value,[3,8]))
np.where(np.isin(f['frame1']['class_ids'].value,[3,8]))

[ 8  3  1 10  1  1  1  1  3  3]
[ True  True False False False False False False  True  True]


(array([0, 1, 8, 9]),)

In [12]:
f.close()

In [57]:
f2.close()

In [59]:
mot_tracker = Sort()
new_r = {}



save_path = os.path.join(ROOT_DIR, "../Data/")
f2 = h5py.File("{}30SLight1_Tracked_Fewer.hdf5".format(save_path), "r+")

In [26]:
list(f2.keys())

['class_names',
 'frame1',
 'frame10',
 'frame100',
 'frame101',
 'frame102',
 'frame103',
 'frame104',
 'frame105',
 'frame106',
 'frame107',
 'frame108',
 'frame109',
 'frame11',
 'frame110',
 'frame111',
 'frame112',
 'frame113',
 'frame114',
 'frame115',
 'frame116',
 'frame117',
 'frame118',
 'frame119',
 'frame12',
 'frame120',
 'frame121',
 'frame122',
 'frame123',
 'frame124',
 'frame125',
 'frame126',
 'frame127',
 'frame128',
 'frame129',
 'frame13',
 'frame130',
 'frame131',
 'frame132',
 'frame133',
 'frame134',
 'frame135',
 'frame136',
 'frame137',
 'frame138',
 'frame139',
 'frame14',
 'frame140',
 'frame15',
 'frame16',
 'frame17',
 'frame18',
 'frame19',
 'frame2',
 'frame20',
 'frame21',
 'frame22',
 'frame23',
 'frame24',
 'frame25',
 'frame26',
 'frame27',
 'frame28',
 'frame29',
 'frame3',
 'frame30',
 'frame31',
 'frame32',
 'frame33',
 'frame34',
 'frame35',
 'frame36',
 'frame37',
 'frame38',
 'frame39',
 'frame4',
 'frame40',
 'frame41',
 'frame42',
 'frame43',

In [31]:
relevant_masks = np.where(np.isin(f2["frame1"]['class_ids'].value,[3,8]))[0]
print(relevant_masks)
print(f2["frame1"]['class_ids'].value)
f2["frame1"]['class_ids'].value[relevant_masks]

[0 1 8 9]
[ 8  3  1 10  1  1  1  1  3  3]


array([8, 3, 3, 3], dtype=int32)

In [46]:
f = h5py.File("{}30SLight1_Fewer.hdf5".format(save_path), "w")
f.create_dataset("class_names",data= f2["class_names"])
for key in list(f2.keys()):
    if (key == 'class_names'):
        continue
    relevant_masks = np.where(np.isin(f2[key]['class_ids'].value,[3,8,10]))[0]
    f.create_dataset("{}/class_ids".format(key), data =f2[key]['class_ids'].value[relevant_masks])
    f.create_dataset("{}/image".format(key), data = f2[key]["image"].value)
    f.create_dataset("{}/rois".format(key), data = f2[key]["rois"].value[relevant_masks])
    f.create_dataset("{}/scores".format(key), data = f2[key]["scores"].value[relevant_masks])
    f.create_dataset("{}/masks".format(key), data = f2[key]["masks"].value[:,:,relevant_masks])

In [56]:
f.close()

In [48]:
f = h5py.File("{}30SLight1_Fewer.hdf5".format(save_path), "r")

In [ ]:
def get_mask_area(mask):
    return np.sum(mask)

In [49]:
mask_list = []
for key in list(f2.keys()):
    if (key == 'class_names'):
        continue
        
    for mask_idx in f2[key]["masks"].value.shape[2]:
        mask_area = get_mask_area(f2[key]["masks"].value[:,:,mask_idx])
        mask_list.append(mask_area)
        
    

['class_names',
 'frame1',
 'frame10',
 'frame100',
 'frame101',
 'frame102',
 'frame103',
 'frame104',
 'frame105',
 'frame106',
 'frame107',
 'frame108',
 'frame109',
 'frame11',
 'frame110',
 'frame111',
 'frame112',
 'frame113',
 'frame114',
 'frame115',
 'frame116',
 'frame117',
 'frame118',
 'frame119',
 'frame12',
 'frame120',
 'frame121',
 'frame122',
 'frame123',
 'frame124',
 'frame125',
 'frame126',
 'frame127',
 'frame128',
 'frame129',
 'frame13',
 'frame130',
 'frame131',
 'frame132',
 'frame133',
 'frame134',
 'frame135',
 'frame136',
 'frame137',
 'frame138',
 'frame139',
 'frame14',
 'frame140',
 'frame15',
 'frame16',
 'frame17',
 'frame18',
 'frame19',
 'frame2',
 'frame20',
 'frame21',
 'frame22',
 'frame23',
 'frame24',
 'frame25',
 'frame26',
 'frame27',
 'frame28',
 'frame29',
 'frame3',
 'frame30',
 'frame31',
 'frame32',
 'frame33',
 'frame34',
 'frame35',
 'frame36',
 'frame37',
 'frame38',
 'frame39',
 'frame4',
 'frame40',
 'frame41',
 'frame42',
 'frame43',

In [54]:
f["frame1"]['masks'].value.shape

(540, 930, 5)

In [60]:
from scipy.spatial import distance

def find_nn(query, array):
    nn = 0
    min_dist = float('inf')
    for i in range(array.shape[0]):
        dist = distance.euclidean(query,array[i,:])
        if ( dist < min_dist):
            nn = i 
            min_dist = dist
    
    return nn
    

In [61]:
for i in range(1,len(list(f2.keys()))):
    key = "frame{}".format(i)
    #relevant_masks = np.where(np.isin(f2[key]['class_ids'].value,[3,6,8,10]))[0]
    bbox_handle = f2[key]['rois']

    
    print("Handling key"+key)
    #print("the relevant masks are at")
    #print(relevant_masks)
    
    detection = bbox_handle.value
    print("the detection is")
    print(detection)
    
    scores = f2[key]['scores'].value
    print("the scores are")
    print(scores)
    number_of_masks= scores.shape[0]
    
    detection_with_scores = np.hstack((detection,np.reshape(scores,(-1,1)) ))
    
    
   
    
    print("the detection with scores is")
    #print(detection_with_scores)
    
    track_bbs_ids = mot_tracker.update(detection_with_scores)

    print("the tracked bbs")
    print (track_bbs_ids)
    
    #Associate the track_BBs with the original bbs
    # for each of the track bbs
    # find the nearest neighbour in the original detections
    #associate the ID with the index of the original detection
    
    index_array = np.zeros(number_of_masks)
    for track in track_bbs_ids :
        nn_index = find_nn(track[:-1], detection)
        print(nn_index)
        index_array[nn_index] = track[-1]
        
    
    print("The index array is")
    print(index_array)
        
    f2.create_dataset("{}/ID".format(key), data = index_array)
 
        
    

Handling keyframe1
the detection is
[[ 57 249 322 587]
 [157  84 220 174]
 [  7  57 114  96]
 [153  29 183  62]
 [145 164 196 221]]
the scores are
[ 0.99814761  0.99663347  0.99046093  0.81966937  0.78696531]
the detection with scores is
the tracked bbs
[[ 145.  164.  196.  221.    5.]
 [ 153.   29.  183.   62.    4.]
 [   7.   57.  114.   96.    3.]
 [ 157.   84.  220.  174.    2.]
 [  57.  249.  322.  587.    1.]]
4
3
2
1
0
The index array is
[ 1.  2.  3.  4.  5.]
Handling keyframe2
the detection is
[[162  76 217 162]
 [  7  57 114  95]
 [ 68 218 309 527]
 [143 160 195 224]
 [147 218 196 252]
 [155  30 184  60]]
the scores are
[ 0.99790478  0.99265242  0.98616308  0.83565497  0.81991816  0.7485795 ]
the detection with scores is
the tracked bbs
[[ 147.          218.          196.          252.            6.        ]
 [ 142.38263671  160.74637996  195.61766293  223.25371992    5.        ]
 [ 155.20597334   29.78164981  183.79372701   60.21845007    4.        ]
 [   7.3269228    56.8827

7
The index array is
[ 21.  15.   3.  25.   0.   9.  12.   2.   0.  20.   0.]
Handling keyframe22
the detection is
[[183 267 276 478]
 [167  78 258 202]
 [  8  57 111  94]
 [161 177 230 256]
 [ 45 441 125 468]
 [ 66 337 131 363]
 [170 278 210 348]
 [125  24 204 109]
 [163 596 379 924]
 [158   0 184  27]]
the scores are
[ 0.99811745  0.99466199  0.99415672  0.99291706  0.99243551  0.98287624
  0.97026056  0.96812326  0.93713462  0.93386877]
the detection with scores is
the tracked bbs
[[  1.59696701e+02   1.80163977e+02   2.31911422e+02   2.51882709e+02
    2.50000000e+01]
 [  1.71807218e+02   2.41525198e+02   2.81729660e+02   4.90172465e+02
    2.10000000e+01]
 [  1.26785356e+02   2.67404552e+01   2.00130953e+02   1.04479973e+02
    2.00000000e+01]
 [  1.59319173e+02   5.68875573e+01   2.58897080e+02   1.97690747e+02
    1.50000000e+01]
 [  6.57782910e+01   3.36901102e+02   1.31219596e+02   3.63064107e+02
    1.20000000e+01]
 [  4.46802132e+01   4.40279739e+02   1.25444436e+02   4.6873

3
1
The index array is
[ 35.   3.  12.   9.  15.   0.  25.   0.   0.]
Handling keyframe39
the detection is
[[166  86 209 160]
 [  6  58 112  95]
 [ 45 442 123 468]
 [ 66 339 130 362]
 [158 263 189 318]
 [161 155 233 261]
 [168 291 217 354]
 [156   8 204  84]
 [161  72 193  97]
 [136   0 188  47]]
the scores are
[ 0.99677074  0.99172795  0.98943126  0.98781812  0.9844892   0.95894867
  0.94220281  0.9371202   0.89672524  0.75214922]
the detection with scores is
the tracked bbs
[[  1.66063955e+02   2.88614193e+02   2.18711306e+02   3.56105844e+02
    3.80000000e+01]
 [  1.65902974e+02   8.43362844e+01   2.08428552e+02   1.59781502e+02
    3.50000000e+01]
 [  1.64129880e+02   6.91995726e+01   1.89805198e+02   9.32007511e+01
    2.50000000e+01]
 [  1.46865164e+02  -3.17885255e-01   1.87789472e+02   4.86306183e+01
    1.50000000e+01]
 [  6.66289026e+01   3.39187048e+02   1.28986878e+02   3.61994734e+02
    1.20000000e+01]
 [  4.47455954e+01   4.42285332e+02   1.23231950e+02   4.67829947e+02

the tracked bbs
[[ 159.1404157    26.46183056  192.7947451    62.97467283   44.        ]
 [ 152.36334707  505.6581128   444.48710827  926.64355551   42.        ]
 [ 157.75817219   70.39673404  200.97586413  132.27161137   40.        ]
 [  66.58102902  339.16204055  128.09090262  362.18372131   12.        ]
 [  45.69665093  442.60353232  123.56864799  467.64148056    9.        ]
 [   6.38596581   57.8423503   112.60421699   94.51293114    3.        ]]
4
5
3
1
2
0
The index array is
[  3.  12.   9.  40.  44.  42.]
Handling keyframe56
the detection is
[[  6  58 112  95]
 [ 46 443 123 468]
 [ 67 339 128 362]
 [157  71 203 130]
 [160  36 198  72]
 [168 508 436 925]]
the scores are
[ 0.99278176  0.98808509  0.98800755  0.98373622  0.8492232   0.80936891]
the detection with scores is
the tracked bbs
[[ 160.56245419   32.21920699  195.4081982    68.59740595   44.        ]
 [ 154.54347901  499.54887725  444.89539986  926.49502484   42.        ]
 [ 158.33338613   69.36089243  200.5612475   127.9

[[ 161.15304709    4.00838768  189.56193416   40.92037917   44.        ]
 [ 160.86992474  489.64924117  437.0788685   932.43814129   42.        ]
 [ 162.2651143    38.57767577  190.39842414   69.11554407   40.        ]
 [  66.14508612  339.02330425  128.84948767  362.36951557   12.        ]
 [  45.86905337  442.64316023  123.15078628  468.00269947    9.        ]
 [   6.87226614   58.71219732  111.47452981   94.53659154    3.        ]]
5
4
3
2
1
0
The index array is
[  3.   9.  12.  40.  42.  44.]
Handling keyframe78
the detection is
[[  7  58 112  95]
 [ 46 442 123 468]
 [ 67 339 128 363]
 [158  37 192  71]
 [161 496 431 929]
 [164   4 189  40]]
the scores are
[ 0.99395376  0.99057859  0.9882459   0.94837904  0.89089191  0.82769275]
the detection with scores is
the tracked bbs
[[ 162.43661408    3.52955956  189.77767958   40.01727505   44.        ]
 [ 158.73975213  489.94832718  435.17255289  933.14161128   42.        ]
 [ 161.43656819   38.29876888  189.3016143    67.8624097    40.   

3
4
2
1
0
The index array is
[  3.   9.  12.  59.  42.   0.]
Handling keyframe102
the detection is
[[ 46 443 123 468]
 [  6  59 112  94]
 [ 65 339 129 363]
 [165 502 433 930]
 [160  21 188  52]
 [164   1 187  23]]
the scores are
[ 0.99304247  0.99185795  0.98978627  0.89729309  0.88409358  0.81283134]
the detection with scores is
the tracked bbs
[[ 163.36174874    1.52644917  187.37735565   22.17649815   60.        ]
 [ 159.0952673    18.5749106   188.60077129   52.35980696   59.        ]
 [ 162.66264149  499.44643645  436.12798042  933.09829556   42.        ]
 [  65.78209131  339.34034447  128.80932546  362.9220392    12.        ]
 [  45.9736934   442.98658187  123.25688706  468.03813405    9.        ]
 [   6.78162695   58.98810256  111.88179243   94.0623046     3.        ]]
5
4
3
2
0
1
The index array is
[  9.   3.  12.  42.  59.  60.]
Handling keyframe103
the detection is
[[  7  59 111  94]
 [ 66 340 129 362]
 [ 46 443 123 468]
 [165 502 434 930]
 [159  20 187  53]
 [157 144 186 181

the detection is
[[  7  59 113  94]
 [ 46 443 123 468]
 [ 66 339 129 362]
 [160 520 393 879]
 [157  16 190  65]]
the scores are
[ 0.99220395  0.98745549  0.98703092  0.89490473  0.85734797]
the detection with scores is
the tracked bbs
[[  66.15531752  339.274623    128.77203974  361.8432815    12.        ]
 [  46.71247932  442.97242769  122.07135552  468.04170231    9.        ]
 [   7.1734753    59.06856468  112.78503614   93.9351271     3.        ]]
2
1
0
The index array is
[  3.   9.  12.   0.   0.]
Handling keyframe128
the detection is
[[  7  59 113  95]
 [ 46 443 123 468]
 [ 66 339 128 362]
 [163 498 430 930]
 [158  20 187  55]]
the scores are
[ 0.99254155  0.98678756  0.98678499  0.79025203  0.75013316]
the detection with scores is
the tracked bbs
[[ 161.89016954  519.72483098  422.0166255   909.0976579    42.        ]
 [  65.95168007  339.17499659  128.38062217  361.85006024   12.        ]
 [  46.57531285  442.98006633  122.37633045  468.02988943    9.        ]
 [   7.14915293   

In [62]:
f2.close()

In [17]:
f2 = h5py.File("{}30SLight1_Tracked.hdf5".format(save_path), "r")

In [21]:
f2["frame3"]["ID"].value

array([  2.,   4.,   3.,  16.,   1.,   8.,   6.,  11.,  17.,  18.,   5.,
        14.,   9.,  15.,  10.])

In [ ]:
"""for i in range(1,len(list(f2.keys()))+1):
    key = "frame{}".format(i)
    if (key=="class_names"):
        continue
    relevant_masks = np.where(np.isin(f2[key]['class_ids'].value,[3,8]))[0]
    bbox_handle = f2[key]['rois']
    
    print("Handling key"+key)
    print("the relevant masks are at")
    print(relevant_masks)
    
    detection = bbox_handle.value[relevant_masks,:]
    print("the detection is")
    print(detection)
    
    scores = f2[key]['scores'].value[relevant_masks]
    print("the scores are")
    print(scores)
    
    detection_with_scores = np.hstack((detection,np.reshape(scores,(-1,1)) ))
    
    
   
    
    print("the detection with scores is")
    #print(detection_with_scores)
    
    track_bbs_ids = mot_tracker.update(detection_with_scores)
    print("the tracked bbs")
    
        
    print (track_bbs_ids)
    
    
    #for mask_id in relevant_masks[0]:

        
        #bbox_handle[mask_id,:] = track_bbs_ids
        
     #   i+=1
        
    """

In [41]:
f2["frame1"]["rois"]

<HDF5 dataset "rois": shape (10, 4), type "<i4">

In [14]:
f2.close()

NameError: name 'f2' is not defined